#!/usr/bin/env bash

#PBS -l nodes=1:ppn=9:gpus=1:skylake
#PBS -l partition=gpu
#PBS -l walltime=03:00:00
#PBS -l pmem=5gb
#PBS -A lp_socialsleep 

module purge
echo $CONDA_PREFIX
source /data/leuven/333/vsc33399/jupyter/bin/activate
conda activate deepethogram

python -m deepethogram.sequence.inference \
    project.path=${PROJECT_PATH} \
    inference.overwrite=True\
    sequence.weights=latest \
    compute.num_workers=2 \
    inference.ignore_error=False
